version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatop-backend
    volumes:
      - ../..:/workspaces:cached
    env_file: "default.env"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  mysql-server:
    image: mysql:lts
    container_name: mysql-server
    env_file: "default.env"
    volumes:
      - ../src/main/resources/sql/script.sql:/docker-entrypoint-initdb.d/script.sql
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql-data: